runtime: python310
entrypoint: gunicorn src.main:app --timeout 90 -w 1 -k uvicorn.workers.UvicornWorker

env_variables:
  CASSANDRA_HOST: localhost
  CASSANDRA_PORT: 9042
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  KAFKA_HOST: localhost
  KAFKA_PORT: 29092
