version: '3.7'

services:
  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    restart: on-failure
    environment:
      CASSANDRA_CQL_PORT_NUMBER: 9042
      CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_TRANSPORT_PORT_NUMBER: 7000
    healthcheck:
      test: [ "CMD", "/opt/bitnami/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - ./data/cassandra:/bitnami

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  cache:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./data/cache:/data

  app:
    ports:
      - '8080:80'
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  cass-backend:
    driver: bridge
  redis-backend:
    driver: bridge
  broker-kafka:
    driver: bridge

volumes:
  cache:
    driver: local
